### ISSUE TITLE
Null-safety issue with animated translate 

### ISSUE THREAD

**Issue by f69** [ReinBentdal/styled_widget#62]
In 0.3.1 code like:
`SomeWidget(...).translate(offset: ..., animate: true)`
throws:
```
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building _StyledAnimatedBuilder(dependencies: [_StyledInheritedAnimation]):
type 'Null' is not a subtype of type 'AlignmentGeometryTween' in type cast

The relevant error-causing widget was: 
  _StyledAnimatedBuilder file:///Users/ds/.pub-cache/hosted/pub.dartlang.org/styled_widget-0.3.1/lib/src/extensions/widget_extension.dart:861:13
When the exception was thrown, this was the stack: 
#0      _AnimatedTransformState.forEachTween (package:styled_widget/src/animated_widget.dart:263:9)
#1      ImplicitlyAnimatedWidgetState._constructTweens (package:flutter/src/widgets/implicit_animations.dart:427:5)
#2      ImplicitlyAnimatedWidgetState.initState (package:flutter/src/widgets/implicit_animations.dart:381:5)
#3      AnimatedWidgetBaseState.initState (package:flutter/src/widgets/implicit_animations.dart:553:11)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4632:57)
...
```
I think you should change
`as AlignmentGeometryTween;`
to
`as AlignmentGeometryTween?;`
at mentioned in stack trace line 263

**Comment by f69** [comment]
I think the same issue is present for all animated widgets, which have animatable nullable properties.
For example, I have got this with Icon (when it is animated, but size not given in constructor):
```
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building _StyledAnimatedIconContainer(IconData(U+0E856), color: Color(0x1f000000), dependencies: [_StyledInheritedAnimation]):
type 'Null' is not a subtype of type 'Tween<double>' in type cast

The relevant error-causing widget was: 
  CircleButton file:///Users/ds/src/flutter/projects/letters_pro_3/lib/components/game_buttons.dart:63:9
When the exception was thrown, this was the stack: 
#0      _AnimatedIconState.forEachTween (package:styled_widget/src/animated_icon.dart:91:9)
#1      ImplicitlyAnimatedWidgetState._constructTweens (package:flutter/src/widgets/implicit_animations.dart:427:5)
#2      ImplicitlyAnimatedWidgetState.initState (package:flutter/src/widgets/implicit_animations.dart:381:5)
#3      AnimatedWidgetBaseState.initState (package:flutter/src/widgets/implicit_animations.dart:553:11)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4632:57)
...
====================================================================================================
```

**Comment by ReinBentdal** [comment]
Thanks for reporting the problem. Could you provide some more code, to give context to the issue? Do you for example use `.animate()` as an ancestor?

**Comment by f69** [comment]
```
import 'package:flutter/material.dart';
import 'package:styled_widget/styled_widget.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: HomePage());
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  bool _darkSide = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Test')),
      body: [
        Text('Test')
            .translate(offset: Offset(_darkSide ? -50 : 50, 0), animate: true)
            .animate(Duration(seconds: 1), Curves.ease),
        Styled.icon(Icons.cloud,
                color: _darkSide ? Colors.red : Colors.green, animate: true)
            .animate(Duration(seconds: 1), Curves.ease),
      ].toColumn(mainAxisSize: MainAxisSize.min).center(),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.refresh),
        onPressed: () => setState(() => _darkSide = !_darkSide),
      ),
    );
  }
}

```

**Comment by f69** [comment]
I am migrating one project to null safety. And have found it not so straightforward as it might seem using dart tools - there are many such pitfalls.

**Comment by esDotDev** [comment]
This line is causing this error for me:
```
.translate(offset: Offset.zero, animate: true)
.animate(.1.seconds, Curves.easeOut)
```

**Comment by ReinBentdal** [comment]
This should now be fixed in the latest hot-fix. @f69 could you verify that your issue is resolved?

**Comment by f69** [comment]
Now it works fine. Thanks a lot!
